services:
  - type: web
    name: all4you-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://www.all4youauctions.co.za
      - key: NEXT_PUBLIC_BASE_URL
        value: https://www.all4youauctions.co.za
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: EMAIL_DEBUG
        value: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_FROM
        value: admin@all4youauctions.co.za
    # Set these sensitive variables manually in Render Dashboard:
    # SMTP_USER=admin@all4youauctions.co.za
    # SMTP_PASS=your-google-app-password
